n = input('Digite algo: ')
print(type(n))
print('É um número: {}'.format(n.isnumeric()))
print('É uma letra: {}'.format(n.isalpha()))
print('É alphanumérico: {}'.format(n.isalnum()))
print('Tem somente letras maiúsculas: {}'.format(n.isupper()))
print('Tem somente letras minusculas: {}'.format(n.islower()))
print('Pode ser impresso: {}'.format(n.isprintable()))
print('É um espaço: {}'.format(n.isspace()))
print('É um digito: {}'.format(n.isdigit()))
print('É um identificador: {}'.format(n.isidentifier()))
print('É um título: {}'.format(n.istitle()))